### ISSUE TITLE
Could not find artifact org.aksw.simba:BENGAL:pom:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by HongAHongzhiyu** [dice-group/COPAAL#6]
Hello, thank you for the contributions you've made. Without any doubt, this project makes great achievement in KB error detection. However, when I ran your source code in my computer, errors showing "Could not find artifact org.aksw.simba:BENGAL:pom:1.0-SNAPSHOT" happened. Therefore, would it possible for you to offer some support with respect to this problem？Thank you very much.

**Comment by MichaelRoeder** [comment]
Yes, that is a known problem of the master version. You could check out the `develop` branch which has a fix for that. If you want to use exactly the version of the paper, you can also rely on the current master version and add the changes from https://github.com/dice-group/COPAAL/pull/7/commits/ead75fdbb104032d587ae1d04cc0d5930eb85365 

Let us know if that fixes your problem.

**Comment by HongAHongzhiyu** [comment]
It's very kind of you to help me solve this problem. I made a try to solve the problem by adding the changes, but the IDE told me "Failure to find joda-time:joda-time:pom:2.10.1 .etc." This may be because my slow network. I wil try again when the network is OK. Or the develop branch may be a good choice. Anyway, thank you very much for your reply.  When the pronlem is solved, I will let you know soon.

**Comment by HongAHongzhiyu** [comment]
> Yes, that is a known problem of the master version. You could check out the `develop` branch which has a fix for that. If you want to use exactly the version of the paper, you can also rely on the current master version and add the changes from [ead75fd](https://github.com/dice-group/COPAAL/commit/ead75fdbb104032d587ae1d04cc0d5930eb85365)
> 
> Let us know if that fixes your problem.

Hello，This problem has been solved with your kind help.  However，when I began to use this program，it told “Whitelabel Error Page 
This application has no explicit mapping for /error, so you are seeing this as a fallback.”  on my browser. I think it may be because of the sparql-end-point in the "application.property". Would it possible for you to help me to solve this problem?
Anyway, I am so grateful for your previous help.
Best Wishes.
![image](https://user-images.githubusercontent.com/50492398/88784221-5c435a80-d1c2-11ea-9383-740f3039f1ee.png)

**Comment by MichaelRoeder** [comment]
The part in the brackets `type=Not Found, status=404` indicates that the page you are trying to open does not exist. It is important to mention that the fact checking service itself does not offer any web page or something similar. What you can do is call the `/validate` with a linkt similar to the one mentioned in https://github.com/dice-group/COPAAL#using-the-maven-plugin
When you open this link, your browser calls the `/validate` method of the service and gives the triple 
`http://dbpedia.org/resource/Barack_Obama http://dbpedia.org/ontology/nationality http://dbpedia.org/resource/United_States` and a path length of 2. The response should be a veracity score.

Why do you think that the error is related to the SPARQL endpoint? Do you have defined a SPARQL endpoint in the application.property file?

**Comment by HongAHongzhiyu** [comment]
> The part in the brackets `type=Not Found, status=404` indicates that the page you are trying to open does not exist. It is important to mention that the fact checking service itself does not offer any web page or something similar. What you can do is call the `/validate` with a linkt similar to the one mentioned in https://github.com/dice-group/COPAAL#using-the-maven-plugin
> When you open this link, your browser calls the `/validate` method of the service and gives the triple
> `http://dbpedia.org/resource/Barack_Obama http://dbpedia.org/ontology/nationality http://dbpedia.org/resource/United_States` and a path length of 2. The response should be a veracity score.
> 
> Why do you think that the error is related to the SPARQL endpoint? Do you have defined a SPARQL endpoint in the application.property file?

In fact, SPARQL endpoint is something what i don’t understand. Therefore I'm not sure how to define a SPARQL endpoint. In the application.property file, that was defined " info.service.url="http://dbpedia.org/sparql" " as follow: 
![image](https://user-images.githubusercontent.com/50492398/88873997-91968980-d250-11ea-8b7b-269e1473beec.png)
However, that seems to be a incorrect approach because of the following feedback in the browser:
![image](https://user-images.githubusercontent.com/50492398/88874246-3022ea80-d251-11ea-99fa-a98e2c4dc554.png)
Feel so sorry to bother you, but would it possible for you to help me to map the sparql end-point in the application.property or tell me how to do it? 
Best wishes to yours and you.

**Comment by MichaelRoeder** [comment]
COPAAL relies on a reference knowledge base. An easy access to this knowledge base can be given by providing a SPARQL endpoint (i.e., a webservice that answers SPARQL queries). Hence, if you use the SPARQL endpoint `http://dbpedia.org/sparql` the results of COPAAL rely on the current DBpedia.

`info.service.url="http://dbpedia.org/sparql"` looks wrong. Can you please remove the quotation marks? The error message also states that the protocol in the URL is missing, simply because the string starts with `"` which is not a valid part of a URL at this position :wink:

**Comment by HongAHongzhiyu** [comment]
> COPAAL relies on a reference knowledge base. An easy access to this knowledge base can be given by providing a SPARQL endpoint (i.e., a webservice that answers SPARQL queries). Hence, if you use the SPARQL endpoint `http://dbpedia.org/sparql` the results of COPAAL rely on the current DBpedia.
> 
> `info.service.url="http://dbpedia.org/sparql"` looks wrong. Can you please remove the quotation marks? The error message also states that the protocol in the URL is missing, simply because the string starts with `"` which is not a valid part of a URL at this position 😉



> COPAAL relies on a reference knowledge base. An easy access to this knowledge base can be given by providing a SPARQL endpoint (i.e., a webservice that answers SPARQL queries). Hence, if you use the SPARQL endpoint `http://dbpedia.org/sparql` the results of COPAAL rely on the current DBpedia.
> 
> `info.service.url="http://dbpedia.org/sparql"` looks wrong. Can you please remove the quotation marks? The error message also states that the protocol in the URL is missing, simply because the string starts with `"` which is not a valid part of a URL at this position 😉

It's very kind of you to offer help again. When I remove the quotation marks, the browser showed me “java.net.SocketException: Connection reset”. Then I tried to remove the "resource" from the request, it works surprisingly. However, the veracity score is 0 unexpectedly. The result in the browser is as follow：
![image](https://user-images.githubusercontent.com/50492398/89193851-298dcd80-d5d9-11ea-8d9d-2f2a872c030e.png)
And the IDE console result is like this:
![image](https://user-images.githubusercontent.com/50492398/89194047-6f4a9600-d5d9-11ea-85ec-0d9dc960b7e5.png)
The GET request used in the browser is "http://localhost:8080/validate?subject=http://dbpedia.org/Barack_Obama&object=http://dbpedia.org/United_States&property=http://dbpedia.org/ontology/nationality&pathlength=2" where "resource" is removed compared with the one mentioned in https://github.com/dice-group/COPAAL#using-the-maven-plugin. 
I'm not sure if the score is a right one figured out by the program or something I configured is wrong? Besides, would it possible for you to provide the SPARQL endpoint in your running environment?
Best regards. Thank you very much for your kind help.

**Comment by MichaelRoeder** [comment]
`java.net.SocketException: Connection reset` looks like a connection issue. I am not sure where it comes from and I can not reproduce it locally :disappointed: 

Removing "resource" does not really solve an issue. It mainly creates the problem that these two URIs are simply not known by the SPARQL endpoint. Hence, there will be no paths and the result is 0.

You need to figure out where the SocketException comes from. Maybe you can post the complete stack trace of the error here?

**Comment by HongAHongzhiyu** [comment]
Feel sorry to you because I have left my laboratory. I will post the error after I go back. Maybe it needs eight hours since it’s 00:39 here.
Wish you and yours happy everyday.




| |
洪志宇
|
|
邮箱：zhiyu_hong@163.com
|

签名由 网易邮箱大师 定制

On 08/04/2020 00:30, Michael Röder wrote:

java.net.SocketException: Connection reset looks like a connection issue. I am not sure where it comes from and I can not reproduce it locally 😞

Removing "resource" does not really solve an issue. It mainly creates the problem that these two URIs are simply not known by the SPARQL endpoint. Hence, there will be no paths and the result is 0.

You need to figure out where the SocketException comes from. Maybe you can post the complete stack trace of the error here?

**Comment by HongAHongzhiyu** [comment]
Sorry to reply you so long. Here I submit the complete error report in the IDE as follows:
![image](https://user-images.githubusercontent.com/50492398/89243352-51f7e500-d636-11ea-9c39-ba1ac5759f3f.png)
![image](https://user-images.githubusercontent.com/50492398/89243388-663be200-d636-11ea-993d-546bc71d657b.png)
![image](https://user-images.githubusercontent.com/50492398/89243413-7a7fdf00-d636-11ea-9ae7-791e49f54e86.png)
![image](https://user-images.githubusercontent.com/50492398/89243432-84a1dd80-d636-11ea-9e21-5ba49581ebc3.png)

And the browser shows following:
![image](https://user-images.githubusercontent.com/50492398/89243452-8ff50900-d636-11ea-8ff0-21d252a069e0.png)

I'm sorry to disturb you this long time. It's been a great pleasure to work with you.
Best regards.

**Comment by MichaelRoeder** [comment]
> Feel sorry to you because I have left my laboratory.

No problem :wink: 

Just as a hint: you don't have to make screenshots of the console. It is actually better if you copy the text since that makes working with it easier :wink: 

With markdown, you can ensure that it keeps the formatting it has in the console. See https://guides.github.com/features/mastering-markdown/ for more information.

However, from the logs, it looks like there is a connection issue between your machine and the DBpedia server. I am not sure why that happens. Could you please try the following:
* open a browser and open http://dbpedia.org/sparql Do you see a "Virtuoso SPARQL Query Editor" window? Or do you have issues to connect to it? If not, you may have a general connection problem between your machine and the DBpedia server that is independent of COPAAL.
* could you please try to check out the `develop` branch, build the service again (using `mvn clean package` in the service directory) and try it again?

**Comment by HongAHongzhiyu** [comment]
Firstly, thank you the advice, but I think I need time to get used to markdown. 

Besides, I have checked out the develop branch, and try it agan. But the same question happened that showed the "connection reset"😞  I can see the "Virtuoso SPARQL Query Editor" in my browser and some query can be accessed, however others like "select ?p ?o where { <http://dbpedia.org/resource/Alabama> ?p ?o . }"  are not accessed. Therefore, just like what you said, I do have a connection problem. I will try to solve the problem through VPN.

Thank you for your continued help. I will let you know at once when the problem is solved😉

Best regards.
